import { test, expect, type Page } from '@playwright/test';

// Visual baselines are chromium-only and generated by CI inside the pinned
// Playwright Linux container (add the `update-snapshots` PR label). Local macOS
// font rendering differs, so these never run outside CI.
test.skip(!process.env.CI, 'Visual baselines are CI-generated (Linux container)');
test.skip(({ browserName }) => browserName !== 'chromium', 'Visual baselines are chromium-only');

// Viewport-gated content (the IntersectionObserver-deferred mermaid diagram)
// only renders once scrolled near — walk the page and wait for it to settle
// before capturing, so fullPage screenshots are deterministic.
async function settleLazyContent(page: Page): Promise<void> {
  // Scroll each placeholder into view (an instant jump to the page bottom
  // skips past mid-page diagrams without ever intersecting) and wait for the
  // rendered diagram to replace it. waitFor(hidden) also accepts detachment.
  const placeholders = page.getByText('Rendering diagram…');
  while ((await placeholders.count()) > 0) {
    const first = placeholders.first();
    await first.scrollIntoViewIfNeeded();
    await first.waitFor({ state: 'hidden' });
  }
  await page.evaluate(() => window.scrollTo(0, 0));
}

const pages = [
  { name: 'home', path: '/' },
  { name: 'projects', path: '/projects' },
  { name: 'project-detail', path: '/projects/arun-dev-platform' },
  { name: 'articles', path: '/articles' },
  { name: 'article-detail', path: '/articles/react-server-components-deep-dive' },
  { name: 'search', path: '/search' },
  { name: 'achievements', path: '/achievements' },
] as const;

test.describe('Visual snapshots', () => {
  for (const { name, path } of pages) {
    test(`${name} — desktop`, async ({ page }) => {
      await page.goto(path);
      await page.waitForLoadState('networkidle');
      await settleLazyContent(page);
      await expect(page).toHaveScreenshot(`${name}-desktop.png`, { fullPage: true });
    });
  }

  test('home — dark theme', async ({ page }) => {
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await settleLazyContent(page);
    await expect(page).toHaveScreenshot('home-dark.png', { fullPage: true });
  });

  test('home — mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await settleLazyContent(page);
    await expect(page).toHaveScreenshot('home-mobile.png', { fullPage: true });
  });

  test('article-detail — mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/articles/react-server-components-deep-dive');
    await page.waitForLoadState('networkidle');
    await settleLazyContent(page);
    await expect(page).toHaveScreenshot('article-detail-mobile.png', { fullPage: true });
  });
});
