import { test, expect } from '@playwright/test';

// Visual baselines are chromium-only and generated by CI inside the pinned
// Playwright Linux container (add the `update-snapshots` PR label). Local macOS
// font rendering differs, so these never run outside CI.
test.skip(!process.env.CI, 'Visual baselines are CI-generated (Linux container)');
test.skip(({ browserName }) => browserName !== 'chromium', 'Visual baselines are chromium-only');

const pages = [
  { name: 'home', path: '/' },
  { name: 'projects', path: '/projects' },
  { name: 'project-detail', path: '/projects/arun-dev-platform' },
  { name: 'articles', path: '/articles' },
  { name: 'article-detail', path: '/articles/react-server-components-deep-dive' },
  { name: 'search', path: '/search' },
  { name: 'achievements', path: '/achievements' },
] as const;

test.describe('Visual snapshots', () => {
  for (const { name, path } of pages) {
    test(`${name} — desktop`, async ({ page }) => {
      await page.goto(path);
      await page.waitForLoadState('networkidle');
      await expect(page).toHaveScreenshot(`${name}-desktop.png`, { fullPage: true });
    });
  }

  test('home — dark theme', async ({ page }) => {
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveScreenshot('home-dark.png', { fullPage: true });
  });

  test('home — mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/');
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveScreenshot('home-mobile.png', { fullPage: true });
  });

  test('article-detail — mobile', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/articles/react-server-components-deep-dive');
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveScreenshot('article-detail-mobile.png', { fullPage: true });
  });
});
